[pyprland]
plugins = [
  "scratchpads",
]

[scratchpads.terminal]
animation = "fromTop"
command = "ghostty"
class = "com.mitchellh.ghostty"
size = "900px 600px"
unfocus = "hide"
hysteresis = 0
multi = false